spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/board
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 1000

  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: 112.172.174.188
      port: 6379
file:
  root:
    path: D:/file
  upload:
    path: /upload/
  store:
    path: /store/
---
spring:
  config:
    activate:
      on-profile: test
  data:
    redis:
      host: localhost
      port: 6379
